version: "3.8"

services:
    app:
        build:
            context: .
        image: laravel-api-docker
        container_name: laravel-api
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        networks:
            - laravel-net
        environment:
            - DB_CONNECTION=sqlite
            - DB_DATABASE=/var/www/html/database/database.sqlite
        depends_on:
            - db
            - mail

    db:
        image: nouchka/sqlite3
        container_name: sqlite-db
        volumes:
            - ./database:/database
        networks:
            - laravel-net

    mail:
        image: bytemark/smtp
        container_name: smtp
        environment:
            - MAILER_HOST=smtp
        networks:
            - laravel-net

networks:
    laravel-net:
        driver: bridge
